# Generated by Django 4.1.5 on 2023-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ai_response',
            field=models.TextField(null=True, verbose_name='User Input'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_input',
            field=models.TextField(null=True, verbose_name='User Input'),
        ),
    ]
